app.security.actuator-public=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
